### ISSUE TITLE
the new life canlderfj

### ISSUE THREAD

**Issue by a-art** [wcoder/life-calendar#6]
Hi,

I designed a few logos for your software. If you want to use one of these, I can send you a pr.
![img_20180521_144720](https://user-images.githubusercontent.com/39433932/40298881-5165e066-5d06-11e8-9e30-1d677346a4c0.jpg)

**Comment by yauhenipakala** [comment]
Hi @a-art thank you for a proposal.

But I think new logo doesn't need.

**Comment by a-art** [comment]
ok, sir
